// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Event struct {
	ID        int64
	Type      int64
	FilePath  sql.NullString
	FileSize  sql.NullInt64
	Text      sql.NullString
	Meta      sql.NullString
	Processed bool
}

type User struct {
	ID      int64
	Login   string
	Lang    string
	Created time.Time
	Updated time.Time
}
